final/urls.py
from django.urls import path

from . import views

app_name = 'final'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_path/', views.create_path, name='create_path')
]

quantum_bogosort_final/urls.py
from django.contrib import admin
from django.urls import path, include

import final

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('final.urls')),
]

final/models.py
import json
from urllib.request import urlopen

from django.contrib.sites import requests
from django.db import models


# Create your models here.

class Stop(models.Model):
    lastUpdate = None
    stopId = models.IntegerField(primary_key=True)
    stopName = models.CharField(max_length=200)
    subName = models.CharField(max_length=200)
    stopLat = models.FloatField()
    stopLon = models.FloatField()
    nonpassenger = models.BooleanField()

    def __str__(self):
        return self.stopName + ' ' + self.subName


class Route(models.Model):
    stop1 = models.CharField(max_length=400)
    stop2 = models.CharField(max_length=400)
    line = models.CharField(max_length=20)

    def __str__(self):
        return str(self.stop1) + ' -> ' + str(self.stop2) + ' l: ' + self.line


class Incident(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    date = models.DateField()

    def __str__(self):
        return str(self.title)

final/views.py
from . import services
from django.shortcuts import render, redirect
from .models import Stop, Route


def index(request):
    incidents = services.get_info_about_incidents()
    stops_dict = services.get_serialized_stop_info()
    context = {'stops': Stop.objects.all().order_by('stopName', 'subName'), 'stops_dict': stops_dict,
               'incidents': incidents}
    return render(request, 'final/index.html', context)


def create_path(request):
    if request.method == 'POST':
        start = request.POST['starting-route']
        end = request.POST['ending-route']
        s1 = Stop.objects.get(stopId=start)
        s2 = Stop.objects.get(stopId=end)
        start_name = s1.stopName + " " + s1.subName
        end_name = s2.stopName + " " + s2.subName
        max_changes = request.POST['max_changes']
        max_waiting_time = request.POST['max_waiting_time']
        max_distance_on_foot = request.POST['max_distance_on_foot']
        context = services.create_path(start, end, max_changes, max_waiting_time, max_distance_on_foot)
        return render(request, 'final/trasa.html', context)
    return render(request, 'final/index.html')

templates/final/includes/footer.html
    <footer>
        <div class="copyrights">
            <p>&copy; 2023 Quantum Bogosort</p>
        </div>
    </footer>

    <div id="incidents-popup">
        <div class="incidents-popup-content">
            <p id="incidents-text">Na obecną chwilę nie ma żadnych ogłoszeń.<br>Zyczymy miłego dnia :)</p>
            <a class="incidents-popup-close">&#9587;</a>
        </div>
    </div>

    <div id="incidents-button">!</div>
    <script>
        function showIncidents() {
            let text = "Na obecną chwilę nie ma żadnych ogłoszeń.<br>Zyczymy miłego dnia :)";
            document.getElementById("incidents-text").innerHTML = text;
            document.getElementById("incidents-popup").style.display = "block";
            window.setTimeout(function(){
                document.getElementById("incidents-popup").style.opacity = 1;
            }, 50);
            //let popup = constructPopup(text);
            //document.querySelector("body").appendChild(popup);
        }


        /*function constructPopup(text) {
            let popup = document.createElement("div");
            popup.classList.add("incidents-popup");

            let popupContent = document.createElement("div");
            popupContent.classList.add("incidents-popup-content");
            popup.appendChild(popupContent);

            let popupText = document.createElement("p");
            popupText.innerHTML = text;
            popupContent.appendChild(popupText);

            let closePopupButton = document.createElement("a");
            closePopupButton.classList.add("incidents-popup-close");
            closePopupButton.innerHTML = "&#9587;";
            closePopupButton.addEventListener("click", hidePopup());
            popupContent.appendChild(closePopupButton);

            return popup;
        }*/


        function hidePopup() {
            document.getElementById("incidents-popup").style.opacity = 0;
            window.setTimeout(function(){
                document.getElementById("incidents-popup").style.display = "none";
            }, 550);
        }


        let incidentsButton = document.getElementById("incidents-button");
        incidentsButton.addEventListener("click", showIncidents);
        
        let incidentsCloseButton = document.querySelector("#incidents-popup .incidents-popup-close");
        incidentsCloseButton.addEventListener("click", hidePopup);
    </script>
</body>
</html>

templates/final/includes/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Droga do celu</title>
    {% load static %}
    {{ stops_dict|json_script:"stops-data" }}
    {{ incident }}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@100;300;400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/main.css' %}">
</head>
<body>
    <header>

    </header> 

templates/final/index.html
{% include "final/includes/header.html" %}    
{% load static %}
{% if request.method == 'GET' %}
<h1>Droga do celu</h1>
<form action="{% url 'final:create_path' %}" method="post">
    {% csrf_token %}
    <div class="form-container">
        <div class="form-group-main form-group">
            <div class="form-group-item autocomplete-item">
                <label for="start">Punkt początkowy</label>
                <input type="text" name="start" id="start" class="autocomplete-name" autocomplete="off" required>
                <input type="hidden" name="starting-route" class="autocomplete-id" required>
            </div>
            <div class="form-group-item autocomplete-item">
                <label for="end">Punkt końcowy</label>
                <input type="text" name="end" id="end" class="autocomplete-name" autocomplete="off" required>
                <input type="hidden" name="ending-route" class="autocomplete-id" required>
            </div>
        </div>
        <div class="form-group-additional form-group">
            <h2>Dodatkowe parametry</h2>
            <div class="form-group-item">
                <label for="max_changes">Maksymalna liczba przesiadek</label>
                <input type="number" id="max_changes" name="max_changes" value="0" min="0" max="10">
            </div>
            <div class="form-group-item">
                <label for="max_waiting_time">Maksymalny czas oczekiwania na przesiadkę [min]</label>
                <input type="number" id="max_waiting_time" name="max_waiting_time" value="0" min="0" max="1440">
            </div>
            <div class="form-group-item">
                <label for="max_distance_on_foot">Maksymalny dystans pieszo [m]</label>
                <input type="number" id="max_distance_on_foot" name="max_distance_on_foot" value="0" min="0" max="10000">
            </div>
        </div>
        <div class="form-group-search form-group">
            <div class="form-group-item">
                <label for="search">Szukaj</label>
                <input type="submit" value="Szukaj">
            </div>
        </div>
    </div>
</form>
<script src="{% static '/form.js' %}"></script>
{% endif %}
{% include "final/includes/footer.html" %}

templates/final/trasa.html
{% include 'final/includes/header.html' %}
{% if not route %}
    <div class="route-not-found route-info">
        <h1>Nie znaleziono trasy</h1>
        <p>Przepraszamy, nie znaleźliśmy trasy pomiędzy <span class="route-start-name route-text-info">{{ start_name }}</span> a <span class="route-end-name route-text-info">{{ end_name }}</span> spełniającej podane kryteria: </p>
        <p>(maksymalna liczba przesiadek: <span class="route-text-info">{{ max_changes }}</span>, maksymalny czas oczekiwania na przesiadkę: <span class="route-text-info">{{ max_waiting_time }}</span>,
            maksymalny dystans do pokonania pieszo: <span class="route-text-info">{{ max_distance_on_foot }}</span>).</p>
    </div>
{% else %}
    <div class="route-found route-info">
        <h3>Trasa od <span class="route-start-name route-text-info">{{ start_name }}</span> do <span class="route-end-name route-text-info">{{ end_name }}</span> została znaleziona.</h3>
        <ol class="step-list">
            {% for step in route %}
                <li class="step-list-item">
                {% if step.line == -1 %}
                    <span class="li-container">Przejdź pieszo z <span class="route-text-info">{{ step.stop1 }}</span> do <span class="route-text-info">{{ step.stop2 }}</span>.</span>
                {% else %}
                    <span class="li-container">Wsiądź na <span class="route-text-info">{{ step.stop1 }}</span> do pojazdu linii <span class="route-text-info">{{ step.line }}</span> i wysiadź na <span class="route-text-info">{{ step.stop2 }}</span>.</span>
                {% endif %}
                </li>
            {% endfor %}
        </ol>
    </div>
{% endif %}
<a href="/" class="return-button">Powrót do strony głównej</a>
{% include 'final/includes/footer.html' %}